export const GAME_CONSTANTS = {
  STARTING_ROUND: 1,
  INITIAL_TURN_INDEX: 0,
  MAX_ROUNDS: 3,
  WORD_SELECTION_SECONDS: 6,
  TURN_DURATION_SECONDS: 80,
  ROUND_END_SECONDS: 3,
  CORRECT_GUESS_POINTS: 100,
  GUESS_POINT_STEP: 20,
  MIN_GUESS_POINTS: 20,
  DRAWER_BONUS_PER_GUESS: 25,
};
